/**
 * @brief 主要对界面中使用到的一些枚举类型或常量进行定义
 * 
 */


#ifndef _DENNIS_THINK_UI_COMMON_DEF_H_
#define _DENNIS_THINK_UI_COMMON_DEF_H_
//客户端类型
enum class E_UI_CLIENT_TYPE
{
	CLIENT_TYPE_UNKNOWN = 0,
	CLIENT_TYPE_PC = 1,
	CLIENT_TYPE_IOS = 2,
	CLIENT_TYPE_ANDROID = 3
};

//在线状态
enum class E_UI_ONLINE_STATUS
{
	STATUS_OFFLINE = 0,			//离线
	STATUS_ONLINE = 1,			//在线
	STATUS_INVISIBLE = 2,			//隐身
	STATUS_BUSY = 3,			//忙碌
	STATUS_AWAY = 4,			//离开
	STATUS_MOBILE_ONLINE = 5,			//移动版在线
	STATUS_MOBILE_OFFLINE = 6,			//移动版下线
	STATUS_BOTH = 7			//手机和电脑同时在线
};

enum class E_UI_ONLINE_CLIENT_TYPE //在线客户端类型
{
	ONLINE_CLIENT_UNKONWN,
	ONLINE_CLIENT_PC,
	ONLINE_CLIENT_MOBILE,
	ONLINE_CLIENT_BOTH,
	OFFLINE_CLIENT_BOTH
};

enum class E_UI_LOGIN_TYPE
{
	LOGIN_USE_MOBILE_NUMBER = 0,	//使用手机号登录
	LOGIN_USE_ACCOUNT = 1,	//使用账号登录
};

enum class E_UI_LOGIN_RESULT_CODE	// 登录结果代码
{
	LOGIN_SUCCESS,				// 登录成功
	LOGIN_FAILED,				// 登录失败
	LOGIN_UNREGISTERED,			// 用户未注册
	LOGIN_PASSWORD_ERROR,		// 密码错误
	LOGIN_USER_CANCEL_LOGIN,	// 用户取消登录
	LOGIN_SERVER_REFUSED,		// 服务器拒绝
	LOGIN_SERVER_NOT_RESPONSE	// 服务器未响应
};

enum class E_UI_REGISTER_RESULT_CODE	//注册结果代码
{
	REGISTER_SUCCESS,				//注册成功
	REGISTER_EXIST,					//账号已经存在
	REGISTER_FAILED,				//注册失败
	REGISTER_SERVER_NOT_RESPONSE	//服务器未响应
};


//加好友状态
enum class E_UI_OPERATE_FRIEND
{
	UnKnown,//未知
	Apply,//应用
	Agree,//同意
	Refuse,//拒绝
	Delete,//删除
};

enum class E_UI_ADD_FRIEND_RESULT	//添加好友结果
{
	FIND_FRIEND_NOT_FOUND,  //好友未找到
	FIND_FRIEND_FOUND,      //好友已经找到
	FIND_FRIEND_FAILED,     //查找好友失败

	ADD_FRIEND_SUCCESS, //添加好友成功
	ADD_FRIEND_FAILED   //添加好友失败
};

enum class E_UI_DELETE_FRIEND_RESULT
{
	DELETE_FRIEND_SUCCESS,   //删除好友成功
	DELETE_FRIEND_FAILED     //删除好友失败
};

enum class E_UI_SEND_CHAT_MSG_RESULT		//发送聊天消息结果
{
	SEND_MSG_SUCESS,
	SEND_WHOLE_MSG_FAILED,		//发送整个消息失败
	SEND_IMGAE_FAILED,			//发送图片失败
	SEND_FILE_FAILED			//发送文件失败
};

enum class E_UI_UPLOAD_USER_THUMB_RESULT
{
	UPLOAD_USER_THUMB_RESULT_SUCCESS,  //上传缩略图成功
	UPLOAD_USER_THUMB_RESULT_FAILED    //上传缩略图失败
};

enum class E_UI_SEND_FILE_RESULT
{
	SEND_FILE_FAILED,   //发送文件成功
	SEND_FILE_SUCCESS    //发送文件失败
};

enum class E_UI_RECV_FILE_RESULT
{
	RECV_FILE_FAILED,    //接收文件成功
	RECV_FILE_SUCCESS    //接收文件失败
};

enum class E_UI_GET_USER_INFO_TYPE
{
	USER_INFO_TYPE_SELF,
	USER_INFO_TYPE_FRIENDS,
	USER_INFO_TYPE_GROUP,
	USER_INFO_TYPE_GROUP_MEMBER,
};

enum class E_UI_CHAT_MSG_TYPE
{
	FMG_MSG_TYPE_UNKNOWN=-1,
	FMG_MSG_TYPE_BUDDY=0,//好友消息
	FMG_MSG_TYPE_GROUP,//群组消息
	FMG_MSG_TYPE_MULTI,		//群发消息
	FMG_MSG_TYPE_SESS
};

//文件上传下载类型
enum class E_UI_FILE_ITEM_TYPE
{
	FILE_ITEM_UNKNOWN,
	FILE_ITEM_UPLOAD_CHAT_IMAGE,
	FILE_ITEM_UPLOAD_CHAT_OFFLINE_FILE,
	FILE_ITEM_UPLOAD_USER_THUMB,

	FILE_ITEM_DOWNLOAD_CHAT_IMAGE,
	FILE_ITEM_DOWNLOAD_CHAT_OFFLINE_FILE,
	FILE_ITEM_DOWNLOAD_USER_THUMB,
};

//文件下载返回结果码
enum class E_UI_FILE_DOWNLOAD_RETCODE
{
	FILE_DOWNLOAD_FAILED,
	FILE_DOWNLOAD_SUCCESS,
	FILE_DOWNLOAD_USERCANCEL	//用户取消下载
};

//TODO 暂时没有使用
//文件上传返回结果码,
enum class E_UI_FILE_UPLOAD_RETCODE
{
	FILE_UPLOAD_FAILED,
	FILE_UPLOAD_SUCCESS,
	FILE_UPLOAD_USERCANCEL		//用户取消上传
};

//获取文件md5值结果码
enum class E_UI_GET_FILE_MD5_RETCODE
{
	GET_FILE_MD5_FAILED,
	GET_FILE_MD5_SUCESS,
	GET_FILE_MD5_USERCANCEL
};
//修改个人信息详情
enum class E_UI_MODIFY_USER_INFO_TYPE
{
	MODIFY_NICKNAME = 0x0001,
	MODIFY_GENDER = 0x0002,
	MODIFY_BIRTHDAY = 0x0004,
	MODIFY_SIGNATRUE = 0x0008,
	MODIFY_ADDRESS = 0x0010,
	MODIFY_PHONE = 0x0020,
	MODIFY_EMAIL = 0x0040,
	MODIFY_THUMB = 0x0080
};

enum class E_UI_CHAT_CONFIRM_TYPE
{
	CHAT_CONFIRM_TYPE_SINGLE,		//单聊（包括群组）确认消息类型
	CHAT_CONFIRM_TYPE_MULTI			//群发确认消息类型
};

enum class E_UI_NET_DATA_TYPE
{
	NET_DATA_UNKNOWN,
	NET_DATA_REGISTER,
	NET_DATA_LOGIN,
	NET_DATA_USER_BASIC_INFO,
	NET_DATA_CHANGE_STATUS,
	NET_DATA_GROUP_BASIC_INFO,
	NET_DATA_USER_EXTEND_INFO,
	NET_DATA_FRIENDS_ID,
	NET_DATA_FRIENDS_STATUS,
	NET_DATA_CHAT_MSG,
	NET_DATA_CHAT_CONFIRM_IMAGE_MSG,	//聊天发送完图片后追加的确认信息
	NET_DATA_FIND_FRIEND,
	NET_DATA_OPERATE_FRIEND,
	NET_DATA_HEARTBEAT,
	NET_DATA_UPDATE_LOGON_USER_INFO,
	NET_DATA_TARGET_INFO_CHANGE,
	NET_DATA_MODIFY_PASSWORD,
	NET_DATA_CREATE_NEW_GROUP,
	NET_DATA_OPERATE_TEAM,              //添加新的好友分组
	NET_DATA_MODIFY_FRIEND_MARKNAME,    //修改好友备注名
	NET_DATA_MOVE_FRIEND,               //移动好友至其他分组


	NET_DATA_ADD_FRIEND_NOTIFY_REQ,
	NET_DATA_FRIEND_RECV_TEXT_REQ,
	NET_DATA_FILE
};

enum class E_UI_CONTENT_TYPE
{
	CONTENT_TYPE_UNKNOWN,			    // 未知消息类型
	CONTENT_TYPE_TEXT,				    // 文本类型（包括图文混排类型）
	CONTENT_TYPE_IMAGE_CONFIRM,			// 图片上传成功后的确认消息类型  pc专用 （pc在上传图片成功后 补发的消息 用于去下载  pc和app端都要处理）
	CONTENT_TYPE_FILE,				    // 收到好友发送过来的文件
	CONTENT_TYPE_SHAKE_WINDOW,			// 窗口抖动  pc专用
	CONTENT_TYPE_MOBILE_IMAGE,			// app端发出的图片  （app端发送的图片信息，已经上传好才会发送的这一条  pc接到这个类型可以直接显示）

	CONTENT_TYPE_FONT_INFO,				//pc专用，移动端忽略
	CONTENT_TYPE_FACE,					//pc专用，移动端忽略
	CONTENT_TYPE_CHAT_IMAGE,			//pc专用，移动端忽略

	CONTENT_TYPE_REMOTE_DESKTOP         //远程桌面
};


enum class E_UI_NAME_STYLE
{
	NAME_STYLE_SHOW_NICKNAME_AND_ACCOUNT,		//显示昵称和账号
	NAME_STYLE_SHOW_NICKNAME,					//显示昵称
	NAME_STYLE_SHOW_ACCOUNT						//显示账号
};

enum class E_RichEditType
{
	TEXT,
	FACE,
	IMAGE,
};

#endif